meta-integrity/classes/sign_rpm_ext.bbclass
commit 52bf3b6636f95a(meta-integrity: move gpg keyring initialization
to signing-keys) tried to initialize keyring in the task check_public_keys
of the recipe signing-keys. However, it does work with the recipe
signing-keys only, and GPG_PATH can't be passed to other recipes.
We bring the python anonymous function back, and it makes sure GPG_PATH
is set before signing the packages for every recipe.
=> sign_rpm_ext: set default GPG_PATH if it is not specified

meta-integrity/classes/sign_rpm_ext.bbclass
If "GPG_PATH" is set in the init script, then "signing-keys"
get_public_keys task will execute failed.
So the "GPG_PATH" directory would be created when "GPG_PATH" is set.
The do_get_public_keys failed to import gpg key error information is as following:
----------------------------------------------------------------------------------------
ERROR: signing-keys-1.0-r0 do_get_public_keys: Function failed: Failed to import gpg key
(layers/meta-secure-core/meta-signing-key/files/rpm_keys/RPM-GPG-PRIVKEY-SecureCore):
gpg: fatal: can't create directory
`tmp/deploy/images/intel-corei7-64/.gnupg': No such file or directory
Signed-off-by: Guojian Zhou <guojian.zhou@windriver.com>
=> sign_rpm_ext: Fix the GPG_PATH directory not exist issue

meta-signing-key/classes/user-key-store.bbclass
When the SIGNING_MODEL is set to "user", the signing-keys recipes will
run failed on the get_public_keys task. uks_rpm_keys_dir() function
could not return the right rpm_keys directory when the
SIGNING_MODEL is set to "user".
Signed-off-by: Guojian Zhou <guojian.zhou@windriver.com>
=> Fix the user rpm sign key can not be found issue

meta-signing-key/recipes-support/key-store/key-store_0.1.bb
According to Jia's valuable suggestions to add a condition to control the "sample" and "user" sign mode to create these packages.
1. user key pub rpm package also could be created.
2. The latest bitbake could not support the d.getVar() function nest
call. Such as the following function call always return "None"
d.getVar(d.getVar('RPM_KEY_DIR', True) + '/RPM-GPG-KEY-*', True)
It caused the key-store-rpm-pubkey rpm package could not be created in
the latest oe-core project.
Signed-off-by: Guojian Zhou <guojian.zhou@windriver.com>
=> key-store: Fix two key-store-rpm-pubkey user key issues

meta-signing-key/scripts/create-user-key-store.sh
There is no way to specify a keyname or email address for now, so add more args for them.
=> create-user-key-store.sh: Add arguments to specify gpg's key name and eamil address

meta-tpm/recipes-tpm/openssl-tpm-engine/files/0005-tpm-openssl-tpm-engine-parse-an-encrypted-TPM-key-pa.patch, meta-tpm/recipes-tpm/openssl-tpm-engine/openssl-tpm-engine_git.bb
when openssl-tpm-engine lib is used on an unattended device, there is no
way to input TPM key password. So add this feature to support parse an
encrypted(AES algorithm) TPM key password from env.
The default decrypting AES password and salt is set in bb file.
When we create a TPM key(TSS format), generate a 8 bytes random data
as its password, and then we need to encrypt the password with the same
AES password and salt in bb file.
At last, we set a env as below:
export TPM_KEY_ENC_PW=xxxxxxxx
"xxxxxxxx" is the encrypted TPM key password for libtpm.so.
Signed-off-by: Meng Li <Meng.Li@windriver.com>
@jiazhang0
=> tpm : openssl-tpm-engine: parse an encrypted TPM key password from env

meta/recipes-core/images/kernel-initramfs.bb
The "${S}" is not used for kernel-initramfs and it will
cleanup the kernel source codes if it is specified to
${STAGING_KERNEL_DIR}, thus remove this definition.
Signed-off-by: Fupan Li <fupan.li@windriver.com>
=> kernel-initramfs: fix the issue rm kernel source codes

meta-encrypted-storage/recipes-support/cryptsetup/cryptsetup_%.bbappend
meta-oe layer split the udevrules for lvm2 into a new package.
Add lvm2-udevrules into cryptsetup RDEPENDS list.
Signed-off-by: Jiang Lu <lu.jiang@windriver.com>
=> Add lvm2-udevrules into cryptsetup RDEPENDS list.

meta-encrypted-storage/recipes-base/packagegroups/packagegroup-luks-initramfs.bb, meta/recipes-core/initrdscripts/initrdscripts-secure-core.bb
* install 'packagegroup-tpm2-initramfs' of distro flag 'tpm2' is set
* install 'initrdscripts-ima' if distro flag 'ima' is set
* install 'cryptfs-tpm2-initramfs' if distro flag 'luks' is set
=> Install packages if distro flag set

meta-signing-key/classes/user-key-store.bbclass
Fix warning:
WARNING: xxx do_sign: Function deploy_rpm_keys doesn't exist
=> user-key-store.bbclass: add deploy_rpm_keys

meta-integrity/recipes-support/keyutils/keyutils/keyutils-remove-m32-m64.patch, meta-integrity/recipes-support/keyutils/keyutils/keyutils_fix_library_install.patch, meta-integrity/recipes-support/keyutils/keyutils_git.bb
* rebase patches:
- keyutils_fix_library_install.patch
- keyutils-remove-m32-m64.patch
* append '-Wall' to CFLAGS for fixing:
.../recipe-sysroot/usr/include/features.h:376:4: error: \
#warning _FORTIFY_SOURCE requires compiling with \
optimization (-O) [-Werror=cpp]
* cleanup alternative targets, the *keyring*.7 files have been
removed from keyutils 1.5.10.
=> keyutils: update to 1.5.10

meta-efi-secure-boot/recipes-bsp/grub/grub-efi/mok2verify-support-to-verify-non-PE-file-with-PKCS-7.patch
Fix the error:
mok2verify.c:169:53: error: \
format '%lx' expects argument of type 'long unsigned int', \
but argument 3 has type 'grub_efi_status_t {aka int}' \
[-Werror=format=]
=> grub-efi: fix build error with qemux86

meta-efi-secure-boot/recipes-bsp/shim/shim_git.bb
Fix 32bit assembler errors:
| /tmp/ccJyZFtJ.s: Assembler messages:
| /tmp/ccJyZFtJ.s:268: Error: bad register name `%rsp)'
| /tmp/ccJyZFtJ.s:269: Error: bad register name `%rdi'
...
| make[1]: *** [<builtin>: security_policy.o] Error 1
=> shim: disable OVERRIDE_SECURITY_POLICY for 32bit target

meta-integrity/recipes-core/initrdscripts/files/init.ima
evmctl is able to import DER format certificate only.
Although *.crt doesn't mean its a PEM certificate, but *.der makes more
sense.
=> initrdscripts: rename expected ima certificate

meta-integrity/recipes-base/packagegroups/packagegroup-ima.bb, meta-integrity/recipes-support/ima-inspect/ima-inspect_0.11.bb
ima_inspect is a small program that allows to give a human-readable
representation of the contents of the extended attributes (xattrs) that
the Linux IMA security subsystem creates and manages for files.
=> meta-integrity: Add ima-inspect utility

meta-integrity/recipes-support/ima-inspect/ima-inspect_0.11.bb
The sources require that we have pkgconfig support as well, add missing
inherit.
=> meta-integrity: Fix build problem on ima-inspect

meta-integrity/recipes-support/keyutils/keyutils/keyutils-fix-the-cflags-for-all-of-targets.patch, meta-integrity/recipes-support/keyutils/keyutils/keyutils_fix_x86-64_cflags.patch, meta-integrity/recipes-support/keyutils/keyutils/keyutils_fix_x86_cflags.patch
Refresh the following patches:
keyutils-fix-the-cflags-for-all-of-targets.patch
keyutils_fix_x86-64_cflags.patch
keyutils_fix_x86_cflags.patch
=> keyutils: refresh patches to fix QA warning

README
- You must ensure that RPM is used in PACKAGE_CLASSES.
- We need to remove image-prelink from USER_CLASSES.  Prelinking the
image at creation time (as happens on x86/x86_64) will result in the
IMA hash of files changing from the recorded signature and
verification will fail.
=> README: Clarify local.conf required changes for IMA

meta/recipes-core/initrdscripts/initrdscripts-secure-core.bb
Our "init" script requires additional directories to exist and since we
don't pull in something like base-files that gives us a full layout we
must make these additional directories on our own.
=> initrdscripts-secure-core: Provide all directories init requires

meta-efi-secure-boot/recipes-bsp/efitools/efitools-native_git.bb, meta-efi-secure-boot/recipes-bsp/efitools/efitools.inc, meta-efi-secure-boot/recipes-bsp/efitools/efitools/Fix-for-the-cross-compilation.patch
- In all cases, when building Linux apps (and thus linking with gcc) we
need to pass in the normal set of LDFLAGS for both rpath and link hash
type.
- Rework Fix-for-the-cross-compilation.patch a bit.  When linking EFI
apps (and thus linking with ld) we don't need to pass in other special
flags.  When linking the "openssl" apps we do not need to spell out
the crtN files as gcc handles that for us, they are normal Linux apps.
Ensure that all Linux apps get our EXTRA_LDFLAGS passed in.
With all of these changes we are now able to reuse sstate cache between
build directories.
=> efitools: Rework how we deal with rpath and linking of Linux apps

meta-efi-secure-boot/recipes-bsp/grub/grub-efi/0001-pe32.h-add-header-structures-for-TE-and-DOS-executab.patch, meta-efi-secure-boot/recipes-bsp/grub/grub-efi/mok2verify-support-to-verify-non-PE-file-with-PKCS-7.patch
It fails to build grub-efi for arm64. Add definitions of missing macros
and replace x86 specified asm codes with function grub_halt().
Test by build for arm64 and boot x86-64 image. For the change of mok2verify-support-to-verify-non-PE-file-with-PKCS-7.patch, I don't really know how to test it. But I believe function grub_halt() should work for EFI.
=> grub-efi: fix compile errors for arm64

meta-signing-key/recipes-support/key-store/key-store_0.1.bb
We're missing a leading '-' when we combine pn and ima-privkey here,
add.
Signed-off-by: Michael Grigorov <michael.grigorov@konsulko.com>
=> key-store: Fix typo in key-store-ima-privkey name

meta-efi-secure-boot/recipes-kernel/linux/linux-yocto-efi-secure-boot.inc
To match the usual user experience of having /boot/${KERNEL_IMAGETYPE}
exist as a symlink to the real kernrel, also have our signature file
exist for that as a symlink and include it in the package file.
=> linux-yocto-efi-secure-boot: Package unversioned signature as symlink

meta-efi-secure-boot/recipes-bsp/grub/grub-efi_2.02.bbappend
Functions efi_call_foo and efi_shim_exit are not implemented for arm64
yet, so remove 'aarch64' from COMPATIBLE_HOST for now.
=> grub-efi: remove aarch64 from COMPATIBLE_HOST

meta-integrity/classes/sign_rpm_ext.bbclass
While multiple builds share a common sstate, the latter
build failed to build image which the public key not found.
...
|ERROR: initramfs-ostree-image-1.0-r0 do_rootfs: Importing GPG key failed.
Command 'rpmkeys --root=<path>/rootfs --import <path>/rpm-key' returned 1:
...
The latter build will not regenerate rpm packages and
check_rpm_public_key will not be invoked.
Explicitly invoke check_rpm_public_key at image recipe parsing time,
which make sure gpg public key be imported.
=> sign_rpm_ext.bbclass: check rpm public key at image recipe parsing time

meta-tpm2/recipes-tpm/tpm2-abrmd/files/tpm2-abrmd-init.sh
In addition to the expected /dev/tpmX device nodes, newer Linux kernels now
also create /dev/tpmrmX nodes. This causes the daemon's startup script to
fail, meaning the abrmd daemon is not started automatically.
Signed-off-by: Trevor Woerner <twoerner@gmail.com>
=> tpm2-abrmd-init: fix for /dev/tpmrmX

README, meta-efi-secure-boot/recipes-bsp/grub/grub-efi_2.02.bbappend
It is helpful when secure boot is enabled, because you can not
modify boot command line after boot-menu.inc is signed before deploying.
Signed-off-by: Jinliang Li <jinliang.li@linux.alibaba.com>
=> Add root parameter configuration in boot command line.

meta-signing-key/classes/user-key-store.bbclass
SYSTEM_TRUSTED and SECONDARY_TRUSTED are being incorrectly parsed, so that they are always set to "1".
For instance, if d.getVar("IMA", True) or d.getVar("MODSIGN", True) looks as though it should return false, if both IMA and MODSIGN != "0". However, SYSTEM_TRUSTED is set to "1" instead of "0".
Doing an explicit check of '== 1' fixes this, at the expense of looking ugly. I have tested the opposite; making sure that when the result should be true, the variables are set to 1, and this works as before.
=> Fix parsing bug where SYSTEM_TRUSTED and SECONDARY_TRUSTED were always parsed as true

meta-integrity/recipes-core/util-linux/util-linux_%.bbappend
Specify -no-pie to override possible -pie default.
Signed-off-by: Joe Slater <joe.slater@windriver.com>
=> util-linux: allow -static linking for switch_root.static

meta-tpm2/recipes-tpm/tpm2-abrmd/tpm2-abrmd_git.bb, meta-tpm2/recipes-tpm/tpm2-tools/tpm2-tools_git.bb, meta-tpm2/recipes-tpm/tpm2-tss/tpm2-tss_git.bb
Bitbake will try an ls-remote for any recipe whose SRCREV is AUTOREV,
even if that recipe will not ultimately be used for a particular build.
Therefore if the user specifies 'BB_NO_NETWORK = "1"', the _git versions of
the tpm2 recipes will cause the build to fail even if the _git versions are
not going to be built (which they won't be by default on account of their
DEFAULT_PREFERENCE being set to "-1").
This fix follows the same pattern as
https://github.com/sbabic/meta-swupdate/commit/721fcc89c53debcd6582bd1aa972f75297cf12e9
With this fix, the user can disable networking and successfully build the
non-_git versions of the tpm2 recipes. If the user wants to build the _git
versions, networking must be enabled. The build is expected to fail if the
user asks for the _git versions, but …
=> tpm2 git AUTOREV fix for BB_NO_NETWORK

meta-efi-secure-boot/recipes-bsp/gnu-efi/gnu-efi_%.bbappend, meta-signing-key/recipes-devtools/libsign/libsign_git.bb, meta-signing-key/recipes-devtools/sbsigntool/sbsigntool_git.bb
With this I can do:
TOOLCHAIN_HOST_TASK_append = " nativesdk-libsign nativesdk-libsign-dev"
TOOLCHAIN_HOST_TASK_append += "nativesdk-sbsigntool"
in local.conf and then bitbake -c populate_sdk include sbsign / selsign.  Note that we do need -dev for libsign.so to end up in the SDK and due to now selsign is linked it wants 'libsign.so' and not 'libsign.so.0' or similar.
=> Make efi secure boot tools available to SDKs

meta-encrypted-storage/recipes-support/cryptsetup/cryptsetup_%.bbappend
when configuring lvm2 without udev, lvm2-udevrules package is empty,
causing do_rootfs failure.
Error:
ERROR: wrlinux-image-glibc-std-1.0-r5 do_rootfs: Function failed: do_rootfs
Problem: conflicting requests
- nothing provides lvm2-udevrules needed by cryptsetup-1.7.4-r0.corei7_64
Move lvm2-udevrules from RDEPEND to RRECOMMENDS could workaround the issue.
=> cryptsetup_%.bbappend: move lvm2-udevrules from RDEPEND to RRECOMMENDS

meta-signing-key/recipes-support/key-store/key-store_0.1.bb
After postinst was executed at do_rootfs successfully,
there will be no first boot to redo.
Since `229f4e9 package.bbclass: add support for
pkg_postinst_ontarget()' applied in oe-core, use
pkg_postinst_ontarget to instead.
=> key-store: fix incorrect postpone to first boot

meta-efi-secure-boot/recipes-bsp/efitools/efitools/Build-DBX-by-default.patch
Refresh patch Build-DBX-by-default.patch
=> efitools: refresh patch to fix QA warning

meta-encrypted-storage/recipes-tpm/cryptfs-tpm2/cryptfs-tpm2_git.bb
Now cryptfs-tpm2 supports both TSS 1.x and 2.x API.
Please specify "TSS2_VER=1" in EXTRA_OEMAKE to support 1.x API.
=> cryptfs-tpm2: uprev to 0.7

meta-efi-secure-boot/conf/layer.conf, meta-encrypted-storage/conf/layer.conf, meta-ids/conf/layer.conf, meta-integrity/conf/layer.conf, meta-intel-sgx/conf/layer.conf, meta-signing-key/conf/layer.conf, meta-tpm/conf/layer.conf, meta-tpm2/conf/layer.conf, meta/conf/layer.conf
Since `9ec5a8a layer.conf: Drop sumo from LAYERSERIES_CORENAMES' and
`9867924 layer.conf: Add thud to LAYERSERIES_CORENAMES' applied in oe-core,
update LAYERSERIES_COMPAT `sumo' -> `thud'
=> layer.conf: update LAYERSERIES_COMPAT `sumo' -> `thud'

meta-signing-key/recipes-devtools/libsign/libsign_git.bb
=> libsign: Fix build failure with GCC 8.x

meta-integrity/recipes-devtools/rpm/rpm-integrity.inc
We have a bbappend file which enables plugins for rpm. We need to
ensure to also disable the inhibit plugin for rpm-native. Otherwise,
we get the following warning at rootfs time.
Unable to get systemd shutdown inhibition lock: Socket name too long
The inhibit plugin tries to inhibit shutdown during rpm operation. It
obviously makes no sense for rpm-native, as 1) we may not build on a
systemd based host and 2) the build process does not affect the package
management on host.
Signed-off-by: Chen Qi <Qi.Chen@windriver.com>
=> rpm: disable inhibit plugin for rpm-native

meta/recipes-core/initrdscripts/initrdscripts-secure-core.bb
The following failure is shown during secure-core-image-initramfs:do_rootfs():
Error: Transaction check error:
file /proc conflicts between attempted installs of initrdscripts-secure-core-1.0-r0.corei7_64 and base-files-3.0.14-r89.intel_x86_64
file /sys conflicts between attempted installs of initrdscripts-secure-core-1.0-r0.corei7_64 and base-files-3.0.14-r89.intel_x86_64
So remove /sys and /proc as base-files has already provided them.
=> initrdscripts-secure-core: remove /sys and /proc from package

meta-signing-key/classes/user-key-store.bbclass
Generally speaking, for firmware to import PK/KEK/DB keys they need to
be in the binary "DER" format and typically have the "cer" file
extension.  When deploying our keys, convert what we have to that format
and deploy as well for ease of use.
---
This would be good to merge to all branches once approved, should I send PRs for that or will you just cherry-pick it?  Thanks!
=> meta-signing-key: When deploying keys UEFI keys, deploy DER format

meta-ids/recipes-ids/mtree/mtree/configure.ac-automake-error.patch
It shows warning when apply configure.ac-automake-error.patch:
| WARNING: mtree-1.0.3+gitAUTOINC+4f3e901aea-r0 do_patch:
| ...
| Details:
| Applying patch configure.ac-automake-error.patch
| patching file configure.ac
| Hunk #1 succeeded at 4 with fuzz 2 (offset -2 lines).
Update context of configure.ac-automake-error.patch to sync with current
mtree source codes.
=> mtree: update context of configure.ac-automake-error.patch

meta-efi-secure-boot/recipes-bsp/grub/grub-efi_2.02.bbappend, meta-efi-secure-boot/recipes-bsp/seloader/seloader_git.bb, meta-efi-secure-boot/recipes-core/images/kernel-initramfs.bbappend, meta-efi-secure-boot/recipes-kernel/linux/linux-yocto-efi-secure-boot.inc
In order to deploy our secure boot keys in DER format we need to use
openssl.  This must be listed in our DEPENDS line in order for the
sysroot to be populated correctly when we run do_sign.  Also drop the
explicit fakeroot on our empty grub-efi do_sign as we may not have
globally populated virtual/fakeroot-native at that point in time.
Fixes: 92316d4b402b ("meta-signing-key: When deploying keys UEFI keys, deploy DER format")
=> meta-efi-secure-boot: Ensure openssl-native exists when we need it

meta-tpm2/recipes-tpm/tpm2-abrmd/tpm2-abrmd_2.0.3.bb
Several bug fixes were merged in 2.0.1 and 2.0.3, including the
following PRs that fix building tpm2-abrmd with the musl C library:
https://github.com/tpm2-software/tpm2-abrmd/pull/502
https://github.com/tpm2-software/tpm2-abrmd/pull/503
Signed-off-by: Luca Boccassi <luca.boccassi@microsoft.com>
=> Bump tpm2-abrmd from 2.0.1 to 2.0.3 to fix build with musl

meta-integrity/recipes-support/ima-evm-utils/ima-evm-utils/0001-ima-evm-utils-include-sys-types.h-in-header-to-fix-b.patch, meta-integrity/recipes-support/ima-evm-utils/ima-evm-utils_git.bb
Third party programs including libimaevm fails to build with musl
due to a missing include in the public header. Add it.
The build with glibc is unaffected. Patch sent upstream.
Signed-off-by: Luca Boccassi <luca.boccassi@microsoft.com>
=> Patch ima-evm-utils to fix build with musl

meta/recipes-core/images/kernel-initramfs.bb
...
|install: cannot stat 'tmp-glibc/deploy/images/intel-x86-64/secure-core-image-init
ramfs-intel-x86-64.cpio.gz': No such file or directory
...
Depends do_image_complete after required image generated
=> kernel-initramfs: depends on do_image_complete rather than do_rootfs

meta-efi-secure-boot/recipes-bsp/shim/shim/0001-MokManager-Use-CompareMem-on-MokListNode.Type-instea.patch, meta-efi-secure-boot/recipes-bsp/shim/shim_git.bb
Backport patch to fix build error with gcc9 for option
"-Werror=address-of-packed-member"
MokManager.c: In function 'write_back_mok_list':
MokManager.c:1125:19: error: taking address of packed member of 'struct
<anonymous>' may result in an unaligned pointer value
[-Werror=address-of-packed-member]
1125 |   if (CompareGuid(&(list[i].Type), &CertType) == 0)
|                   ^~~~~~~~~~~~~~~
MokManager.c:1147:19: error: taking address of packed member of 'struct
<anonymous>' may result in an unaligned pointer value
[-Werror=address-of-packed-member]
1147 |   if (CompareGuid(&(list[i].Type), &CertType) == 0) {
|                   ^~~~~~~~~~~~~~~
MokManager.c: In function 'delete_cert':
MokManager.c:1188:19: error: taking address of packed member of 'struct
<anonymous>' may result in an …
=> shim: fix build failure with gcc9

meta-tpm2/recipes-tpm/tpm2-tss/tpm2-tss/0001-build-update-for-ax_code_coverage.m4-version-2019.01.patch, meta-tpm2/recipes-tpm/tpm2-tss/tpm2-tss_2.0.0.bb
After commit [5ef547b autoconf-archive: update to 2019.01.06]
applied in oe-core, there comes below error
when build tpm2-tss:
| NOTE: make -j 48
| Makefile:14636: *** missing separator.  Stop.
So backport a patch from tpm2-tss upstream to fix
this failure.
Signed-off-by: Mingli Yu <Mingli.Yu@windriver.com>
=> tpm2-tss: fix do_compile error

meta-tpm2/recipes-tpm/tpm2-abrmd/files/0001-build-update-for-ax_code_coverage.m4-version-2019.01.patch, meta-tpm2/recipes-tpm/tpm2-abrmd/tpm2-abrmd_2.0.3.bb
After commit [5ef547b autoconf-archive: update to 2019.01.06]
applied in oe-core, there comes below error
when build tpm2-abrmd:
| NOTE: make -j 48
| Makefile:4381: *** missing separator.  Stop.
So backport a patch from tpm2-abrmd upstream to fix
this failure.
Signed-off-by: Mingli Yu <Mingli.Yu@windriver.com>
=> tpm2-abrmd: fix do_compile error

meta-integrity/classes/sign_rpm_ext.bbclass, meta-signing-key/classes/user-key-store.bbclass
The bb.build.FuncFailed had been removed in bitbake with commit
cfeffb602dd5319f071cd6bcf84139ec77f2d170. Use bb.fatal instead of it.
=> meta-secure-core: use bb.fatal instead of bb.build.FuncFailed

meta-efi-secure-boot/recipes-bsp/grub/grub-efi-efi-secure-boot.inc
Fix the following QA issue:
WARNING: grub-efi-2.04-r0 do_package_qa: QA Issue: grub-efi: /boot/efi/EFI/BOOT/grub.cfg.p7b is owned by uid 19183
chown to root for p7b file to fix uid contamination by host.
Signed-off-by: Liwei Song <liwei.song@windriver.com>
=> grub-efi: fix uid contamination by host QA warning

meta-efi-secure-boot/recipes-bsp/seloader/seloader_git.bb, meta-efi-secure-boot/recipes-core/ovmf/ovmf_%.bbappend
Compile EFI drivers from OVMF source, rather than using precompiled binaries from SELoader. This ensures us that they do not contain any miscompiled or malicious code.
=> Use PKCS7 drivers compiled from OVMF source

meta-integrity/README.md, meta-integrity/recipes-base/packagegroups/packagegroup-ima.bb, meta-integrity/recipes-kernel/linux/linux-yocto-integrity.inc, meta-signing-key/recipes-support/key-store/key-store_0.1.bb
Currently `packagegroup-ima` would pull **private keys** into rootfs. Fix this behaviour and stop one to ever pulling private keys into rootfs by dropping `key-store-*-privkey` packages. There is no reason to have them at all.
=> Security: do not install private keys into rootfs

meta-integrity/recipes-kernel/linux/linux-yocto-integrity.inc
Since commit [b41010c linux-yocto-integrity: fix modsign key path] applied,
if MODSIGN_ENABLED is "0", bbclass user-key-store will not be inherited
which causing 'uks_modsign_keys_dir' is not defined
Unconditionally inherit user-key-store, but conditionally invoke
uks_modsign_keys_dir
=> linux-yocto-integrity.inc: fix 'uks_modsign_keys_dir' is not defined

meta-integrity/recipes-support/ima-evm-utils/ima-evm-utils/0001-libimaevm-retrieve-correct-algo-for-v2-signature.patch, meta-integrity/recipes-support/ima-evm-utils/ima-evm-utils_git.bb
When using rpmsign (with --signfiles --fskpath) to sign RPM package,
the IMA signature is not correct, see:
$ getfattr -d -m - rootfs/usr/sbin/grpconv
file: rootfs/usr/sbin/grpconv
security.ima=0sAwIEDy1SEQP3AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA …
=> lib-evm-utils: using the correct algo for v2 signature

meta-efi-secure-boot/recipes-bsp/grub/grub-efi/boot-menu.inc
Currently the recovery menuentry is not available because we don't
provide bzImage_backup and initrd_backup. Remove this entry.
=> grub-efi/boot-menu.inc: remove invalid menuentry

meta-integrity/classes/sign_rpm_ext.bbclass
there is a scenario that this bbclass is enabled globally,
all targets will inherit sign_rpm_ext. but this bbclass
need gpg to work, on some new distro like
ubuntun 19.04, gpg is not installed, so compile will failed.
fail cmd:
cmd = '%s --batch --homedir %s --passphrase %s --import %s' % \
(gpg_bin, gpg_path, d.getVar('RPM_GPG_PASSPHRASE', True), gpg_key)
error:
base-files-3.0.14-r89 do_package_write_rpm: Failed to import gpg key (): /bin/sh: 1: --batch: not found
=> sign_rpm_ext.bbclass: fix compile fail since missing gpg

meta-efi-secure-boot/recipes-core/images/kernel-initramfs-efi-secure-boot.inc
While refactoring the code to eliminate the overlap in the copy of the
.sig and .p7b files the UEFI_SELOADER test was not removed.  This
results in the .sig files not getting copied to the deploy directory
when using the GRUB_SIGN_VERIFY = "1".
All that is needed is to remove the UEFI_SELOADER test statement.
Signed-off-by: Jason Wessel <jason.wessel@windriver.com>
=> kernel-initramfs-efi-secure-boot.inc: Copy .sig files and .p7b

meta-encrypted-storage/recipes-support/cryptsetup/cryptsetup_%.bbappend, meta-signing-key/recipes-devtools/sbsigntool/sbsigntool_git.bb
Joe Slater (1):
sbsigntool-native: specify TMPDIR
Robert Yang (1):
cryptsetup_%.bbappend: Fix for native
meta-encrypted-storage/recipes-support/cryptsetup/cryptsetup_%.bbappend | 2 +-
meta-signing-key/recipes-devtools/sbsigntool/sbsigntool_git.bb          | 2 +-
2 files changed, 2 insertions(+), 2 deletions(-)
=> Misc fixes missing from master branch

meta-efi-secure-boot/recipes-bsp/efitools/efitools.inc, meta-efi-secure-boot/recipes-bsp/efitools/efitools_git.bb
Since commit [382ffa1 efitools: Fix compilation problem with
latest /usr/include/efi], we should apply the fix to native also.
=> efitools-native: Fix compilation problem with latest /usr/include/efi

meta-efi-secure-boot/recipes-bsp/efitools/efitools.inc
If GRUB_SIGN_VERIFY is not enabled, do_sign will fail in which GPG_PATH
is not set (--homedir None)
...
|DEBUG: Executing python function do_sign
|NOTE: Running: echo "SecureCore" | tmp-glibc/hosttools/gpg  --pinentry-mode
loopback --batch --homedir None -u "SecureBootCore" --detach-sign
--passphrase-fd 0 "tmp-glibc/work/core2-32-wrs-linux/efitools/
1.9.2+gitAUTOINC+392836a46c-r0/image/boot/efi/EFI/BOOT/LockDown.efi"
|ERROR: Failed to sign: tmp-glibc/work/core2-32-wrs-linux/efitools/
1.9.2+gitAUTOINC+392836a46c-r0/image/boot/efi/EFI/BOOT/LockDown.efi
...
Since GPG_PATH is set in do_sign's prefunc check_boot_public_key if
GRUB_SIGN_VERIFY is enabled, add the same condition to do_sign
=> efitools: do not do_sign if GRUB_SIGN_VERIFY not enabled

meta-integrity/classes/sign_rpm_ext.bbclass
do_rootfs
in commit 393b80fa, prefuncs of do_package_write_rpm/do_rootfs
have been replace by (task)_prepend in this bbclass, so remove it.
=> sign_rpm_ext.bbclass: remove prefuncs for do_package_write_rpm and

meta-integrity/classes/sign_rpm_ext.bbclass
connect to gpg agent may failed due to the GPG_PATH is too long,
check and raise an error if the length is greater than 80.
Signed-off-by: Liwei Song <liwei.song@windriver.com>
=> sign_rpm_ext.bbclass: check the length of GPG_PATH

meta-integrity/recipes-devtools/rpm/rpm-integrity.inc
Currently, the PACKAGECONFIG assignment in rpm-integrity might overwrite
the previous contents of the variable.
Similar to systemd_%.bbappend and ovmf_%.bbappend, use _append to add
"imaevm" to PACKAGECONFIG when distro feature ima is enabled.
Signed-off-by: Ovidiu Panait <ovidiu.panait@windriver.com>
=> rpm-integrity: Use _append for PACKAGECONFIG

meta-tpm/recipes-tpm/tpm-tools/tpm-tools_git.bb
tpm-tools calls pod2man to produce manual files. But pod2man has been
removed from hosttools in oe-core. So it fails occasionally when in some
certain condition .pod file is newer than corresponding man page files
that man files need to be reproduced:
| make[3]: Entering directory 'TOPDIR/tmp-glibc/work/ppc7400-wrs-linux/tpm-tools/1.3.9.1+gitAUTOINC+bdf9f1bc8f-r0/git/man/man8'
| /bin/bash: pod2man: command not found
| make[3]: *** [Makefile:575: tpm_nvwrite.8] Error 127
Inherit perlnative to fix such issue.
=> tpm-tools: inherit perlnative.bbclass

meta-efi-secure-boot/recipes-core/images/kernel-initramfs-efi-secure-boot.inc
adjust task order to make sure initrd symlink is ready before
do package.
Signed-off-by: Liwei Song <liwei.song@windriver.com>
=> initramfs: adjust task order to aviod initrd symlink unavailable

meta-integrity/classes/sign_rpm_ext.bbclass, meta-signing-key/classes/user-key-store.bbclass
Currently, an error will be thrown when trying to use a GPG homedir whose path
length exceeds 80 characters. This limitation can be worked around by providing
libassuan socket redirection files for "S.gpg-agent.yocto-native",
"S.gpg-agent.ssh", "S.gpg-agent.browser" and "S.gpg-agent.extra"
sockets. The redirection files will point to the real sockets in /tmp
directory. The sockets will be automatically cleaned up by gpg agent.
References:
[1] https://dev.gnupg.org/T1752
[2] https://gnupg.org/documentation/manuals/assuan.pdf
Signed-off-by: Ovidiu Panait <ovidiu.panait@windriver.com>
=> sign_rpm_ext: Use socket redirection to avoid GPG_PATH length limitation

meta-efi-secure-boot/recipes-bsp/grub/grub-efi-efi-secure-boot.inc
In order to create an installable .wic image with secure boot support, it was more convenient for me to deploy also the grub configuration files and certificates into the DEPLOYDIR. From there I could put the files into the image by appending to the IMAGE_BOOT_FILES variable in my local.conf.
=> modified grub-efi-efi-secure-boot.inc to install also the grub configuration files in the DEPLOYDIR

meta-efi-secure-boot/recipes-core/ovmf/ovmf_%.bbappend
If ovmf's do_deploy is run before do_sign, there is a failure
...
|install: cannot stat 'tmp-glibc/work/corei7-64-wrs-linux/ovmf/
edk2-stable201911-r0/ovmf/Pkcs7VerifyDxe.efi.signed': No such file or directory
...
Add do_sign before do_deploy
=> ovmf_%.bbappend: tweak do_sign task order to avoid racing issue

meta-signing-key/classes/user-key-store.bbclass
The gpg-agent daemon will be triggered to run in function boot_sign,
This daemon will not exit even after building project.
So kill the gpg-agent daemon after gpg signing process
at the end of function boot_sign.
Signed-off-by: De Huo <De.Huo@windriver.com>
=> user-key-store.bbclass: Kill gpg agent daemon after gpg sign

meta-signing-key/recipes-support/key-store/key-store_0.1.bb
It shows qa issue when multilib is enabled:
| ERROR: lib32-key-store-0.1-r0 do_package: QA Issue:
lib32-key-store package lib32-key-store-rpm-pubkey - suspicious values 'rpm' in RDEPENDS [multilib]
Prepend MLPREFIX to runtime dependency 'rpm' to fix the issue.
=> key-store: fix rdepends with multilib

meta-tpm2/recipes-tpm/tpm2-tss/tpm2-tss_2.3.2.bb
fix do_package_qa error:
ERROR: QA Issue: tpm2-tss package is not obeying usrmerge distro feature. /lib should be relocated to /usr. [usrmerge]
=> tpm2-tss: support usrmerge

meta-tpm2/recipes-tpm/tpm2-abrmd/tpm2-abrmd_2.3.0.bb
The tpm2-abrmd daemon needs TCTI library for TPM2 device or simulator.
But the libtss2-tcti-device and libtss2-tcti-mssim packages are not
installed by default which causes the tpm2-abrmd daemon startup failure:
systemd[1]: Starting TPM2 Access Broker and Resource Management Daemon...
tpm2-abrmd[459]: tcti_conf before: "device:/dev/tpm0"
tpm2-abrmd[459]: tcti_conf after: "device:/dev/tpm0"
tpm2-abrmd[459]: ERROR:tcti:../tpm2-tss-2.3.2/src/tss2-tcti/tctildr.c:418:Tss2_TctiLdr_Initialize_Ex() Failed to instantiate TCTI
tpm2-abrmd[459]: init_thread_func: failed to create TCTI with conf "device:/dev/tpm0"
tpm2-abrmd[459]: g_bus_unown_name: assertion 'owner_id > 0' failed
Add libtss2-tcti-device and libtss2-tcti-mssim to runtime dependencies.
=> tpm2-abrmd: rdepends on libtss2-tcti-device and libtss2-tcti-mssim

meta-tpm/recipes-tpm/trousers/trousers_git.bb
Security fixes:
CVE-2020-24332
If the tcsd daemon is started with root privileges,
the creation of the system.data file is prone to symlink attacks
CVE-2020-24330
If the tcsd daemon is started with root privileges,
it fails to drop the root gid after it is no longer needed
CVE-2020-24331
If the tcsd daemon is started with root privileges,
the tss user has read and write access to the /etc/tcsd.conf file
=> trousers: update to latest git rev

meta-signing-key/scripts/create-user-key-store.sh
Replace weak des3 encryption with more secure algorithm aes256 to
generate ima key in script create-user-key-store.sh.
Signed-off-by: David Dunlap <david.dunlap@windriver.com>
=> create-user-key-store.sh: replace weak des3 encryption with aes256

meta-tpm2/recipes-tpm/tpm2-abrmd/files/0001-Remove-obsolete-setting-regarding-the-Standard-Outpu.patch, meta-tpm2/recipes-tpm/tpm2-abrmd/tpm2-abrmd_2.3.2.bb
The Standard output type "syslog" is obsolete, causing a warning since systemd
version 246 [1].
Please consider using "journal" or "journal+console"
[1] https://github.com/systemd/systemd/blob/master/NEWS#L202
Signed-off-by: Mingli Yu <mingli.yu@windriver.com>
=> tpm2-abrmd: Remove obsolete setting regarding the Standard Output

meta-tpm/recipes-tpm/trousers/trousers_git.bb
gcc-10 uses '-fno-common' by default, causing build error of
multiple definition. Use '-fcommon' to fix this problem.
Signed-off-by: Chen Qi <Qi.Chen@windriver.com>
=> trousers: fix build failure for gcc-10

meta-efi-secure-boot/recipes-bsp/grub/grub-efi-efi-secure-boot.inc
If we do adopt path filtering for pseudo, we may filter out ${DEPLOY_DIR}
as not needing to be tracked for "root" permissions. but we do track
the data in ${D} though, when we copy file from ${D} to ${DEPLOY_DIR},
pseudo report a failure
...
|cp: failed to preserve ownership for 'tmp-glibc/work/corei7-64-wrs-linux/
grub-efi/2.04-r0/deploy-grub-efi/efi-unsigned/x86_64-efi/fdt.lst'
: Operation not permitted
...
Disable pseudo for the copy operation
=> grub-efi-efi-secure-boot.inc: Adapt to potential psuedo changes

meta-signing-key/classes/user-key-store.bbclass
If GPG_PATH is already created by signing-keys do_get_public_keys task,
subsequent executions of do_package_write_rpm will not create the
gpg-agent.conf file anymore.
Therefore, the spawned gpg-agent will miss important features such as
auto-expand-secmem, leading to the following intermittent build errors:
....
Subprocess output:
gpg: signing failed: Cannot allocate memory
gpg: signing failed: Cannot allocate memory
error: gpg exec failed (2)
gpg: signing failed: Cannot allocate memory
gpg: signing failed: Cannot allocate memory
error: gpg exec failed (2)
...
Signed-off-by: Ovidiu Panait <ovidiu.panait@windriver.com>
=> check_gpg_key: Fix gpg-agent.conf creation race condition

meta-efi-secure-boot/recipes-bsp/grub/grub-efi/mok2verify-support-to-verify-non-PE-file-with-PKCS-7.patch
Refresh mok2verify-support-to-verify-non-PE-file-with-PKCS-7.patch to
adapt the recent CVEs fixing.
=> grub-efi: refresh patch

meta-encrypted-storage/recipes-kernel/linux/linux-yocto/dmcrypt.cfg
CONFIG_HW_RANDOM_TPM is bool, not tristate, and thus it cannot be
set to "m"
Signed-off-by: Yongxin Liu <yongxin.liu@windriver.com>
=> meta-encrypted-storage: set CONFIG_HW_RANDOM_TPM to "y"

meta-integrity/recipes-devtools/rpm/rpm-integrity.inc, meta-integrity/recipes-devtools/rpm/rpm/macros.ima
Since rpm 4.15, the users can control over the installation of
signatures on config files through a variable named
%_ima_sign_config_files. But this is disabled by default. Add a macro
configuration file to enable it.
=> rpm: apply signatures to config files

meta-signing-key/scripts/create-user-key-store.sh
create-user-key-store.sh: allow user to specify openssl x509 'days' param
--
allow openssl x509 '--days' parameter to be specified via command line argument
Signed-off-by: Corey Cothrum <contact@coreycothrum.com>
=> create-user-key-store.sh: allow user to specify --days param

meta-signing-key/classes/user-key-store.bbclass
Adapt to recent psuedo changes.
Fixes:
ERROR: grub-efi-2.04-r0 do_sign: Failed to import gpg key
gpg: key 9E3086F96EEECC34/9E3086F96EEECC34: error sending to agent: End of file
=> user-key-store.bbclass: exclude ${GPG_PATH} from pseudo database

meta-efi-secure-boot/recipes-bsp/grub/grub-efi-efi-secure-boot.inc
Allows to use other efi target paths than /EFI/BOOT, e.g. /EFI/mydistro
=> Grub: Parameterize prefix dir

meta-signing-key/recipes-devtools/libsign/libsign_git.bb
fix below error caused by: openssl->libsign-native->openssl
DEBUG:	Dependency loop #1 found:
Dependency loop #1 found:
...
oe-core commits "bitbake.conf/python: Drop setting RDEPENDS/RPROVIDES default"
and "native: Stop clearing PACKAGES" refactor usage of RDEPENDS
=> libsign: fix dependency loop error

meta-tpm2/recipes-devtools/tpm2simulator/tpm2simulator-native_git.bb
Classes native/nativesdk must be inherited last to prevent unexpected
behaviour.
Fixes QA warning:
QA Issue: tpm2simulator-native: native/nativesdk class is not inherited
last, this can result in unexpected behaviour. Classes inherited after
native/nativesdk: cmake.bbclass lib_package.bbclass python-dir.bbclass
pythonnative.bbclass [native-last]
=> tpm2simulator-native: fix native inheritance order

meta-ids/recipes-ids/mtree/mtree/0001-compat-glibc-2.33.patch, meta-ids/recipes-ids/mtree/mtree_git.bb
The glibc 2.33 remove macro _STAT_VER_LINUX [1],
do not use it to represent linux system
[1] https://sourceware.org/git/?p=glibc.git;a=blobdiff;f=sysdeps/unix/sysv/linux/bits/stat.h;h=b5426232088df446f502e6aea76a6cf03e71e1c4;hp=240628a6f4c9028a774c26a04a145c24110f669b;hb=8ed005daf0ab03e142500324a34087ce179ae78e;hpb=428985c436f442e91e27173bccaf28f547233586
=> mtree: compat glibc 2.33

meta-signing-key/recipes-devtools/sbsigntool/sbsigntool_git.bb
The current sbsigntool repo is ancient and doesn't support native arm
binaries. Let's switch to the current upstream and adjust the recipe
accordingly, allowing the package to be used in native arm machines
Signed-off-by: Ilias Apalodimas <ilias.apalodimas@linaro.org>
=> sbsigntool: Update to latest and change repos

meta-efi-secure-boot/recipes-core/images/kernel-initramfs-efi-secure-boot.inc
p7b was replaced by the ${SB_FILE_EXT} variable, but one reference
was omitted during the rework.
Fixes: 31d2105b
=> kernel-initramfs: Fix leftover p7b reference

meta-efi-secure-boot/recipes-bsp/grub/grub-efi-efi-secure-boot.inc
- the 'verify' grub module has been renamed to 'pgp' in grub 2.04;
- the 'pgp' grub module is already built-in if GRUB_SIGN_VERIFY is set,
so there's no need to call insmod;
While at it, remove some unnecessary code duplication.
=> grub: Drop useless insmod verify from cfg

meta-efi-secure-boot/recipes-bsp/grub/grub-efi-efi-secure-boot.inc
grub-efi-native does not benefit from the extra code/modules that get built for
secure-boot support, it just increases the build time of the package.
Therefore, mark all secure-boot related procedures in the recipe for
class-target only.
Signed-off-by: Ovidiu Panait <ovidiu.panait@windriver.com>
=> grub-efi: enable secure-boot support only for target builds

meta-efi-secure-boot/recipes-bsp/grub/grub-efi-efi-secure-boot.inc, meta-efi-secure-boot/recipes-bsp/grub/grub-efi/0001-fs-ext2-fix-the-file-not-found-error-when-symlink-fi.patch, meta-efi-secure-boot/recipes-bsp/grub/grub-efi/0001-grub-verify-Add-strict_security-variable.patch, meta-efi-secure-boot/recipes-bsp/grub/grub-efi/Grub-get-and-set-efi-variables.patch, meta-efi-secure-boot/recipes-bsp/grub/grub-efi/mok2verify-support-to-verify-non-PE-file-with-PKCS-7.patch
Gatesgarth still uses grub 2.04.
This reverts commit 4e1cc676dc566de9b9f779d4209dd28fa7a80788.
=> Revert "grub-efi: refresh patches for grub 2.06"

meta-efi-secure-boot/recipes-bsp/grub/grub-efi-efi-secure-boot.inc
This should fix #202 . Here we simply clean the file if the variable GRUB_SIGN_VERIFY_STRICT is set to `0`. This will ensure the `cfg` file to represent the variable state. This will also fix an issue where the embedded configuration would contains the `search.file` twice when the variable `GRUB_SIGN_VERIFY_STRICT=0`
=> prevent contamining the cache with embeded cfg

meta-efi-secure-boot/recipes-bsp/grub/grub-efi-efi-secure-boot.inc
Fix #204 for the gatesgarth branch. The fix is to look if the `SELoader`variable is set to 0. If set  to 0, we do not change the grub image name. In both case, we still deploy an image with the grub prefix image name. This fix is made in the gatesgarth branch, but I did not had the time to test it in the master yet.
=> allow to use the wic plugin

meta-efi-secure-boot/recipes-bsp/grub/grub-efi-efi-secure-boot.inc
Fix #206 . During the deploy task we need to check if the signature file should be present and install them only if they should. This fix is made in the gatesgarth branch, but I did not had the time to test it in the master yet.
=> properly handle the GRUB_VERIFY file

meta-efi-secure-boot/recipes-bsp/grub/grub-efi-efi-secure-boot.inc, meta-efi-secure-boot/recipes-kernel/linux/linux-yocto-efi-secure-boot.inc
1. In #207  I forgot to check the variable in the kernel include. The task would fail if GRUB_SIGN_VERIFY is set to 0. Before #207 , it would crash so this will fix both.
2. Include the #203 path which has been introduce to master, but not in this branch
3. #207 Introduce a typo in the `do_chowboot` which will make the build fail with a host contamination error.
This will make #206 working as expected.
=> Fix the kernel include file

meta-efi-secure-boot/recipes-kernel/linux/linux-yocto-efi-secure-boot.inc
Cherry-pick fix from master branch to gatesgarth (original commit message below):
Task do_sign of linux-yocto depends on variable GPG_PATH. When GPG_PATH
changes, it fails to rerun the task:
| Exception: FileExistsError: [Errno 17] File exists:
| 'bzImage-5.2.24-yocto-standard.p7b' -> '/path/to/tmp-glibc/work/intel_x86_64-wrs-linux/linux-yocto/5.2.x+gitAUTOINC+bbe834c1d2_370ab92a1e-r0/image/boot/bzImage.p7b'
Remove the link file before create it if exists already.
=> linux-yocto-efi-secure-boot.inc: fix rerun failure

meta-tpm2/recipes-tpm/tpm2-tools/files/CVE-2021-3565.patch, meta-tpm2/recipes-tpm/tpm2-tools/tpm2-tools_4.1.3.bb
CVE-2021-3565:
A flaw was found in tpm2-tools in versions before 5.1.1 and before
4.3.2. tpm2_import used a fixed AES key for the inner wrapper,
potentially allowing a MITM attacker to unwrap the inner portion and
reveal the key being imported. The highest threat from this
vulnerability is to data confidentiality.
Reference:
https://nvd.nist.gov/vuln/detail/CVE-2021-3565
Patch from:
https://github.com/tpm2-software/tpm2-tools/commit/c069e4f179d5e6653a84fb236816c375dca82515
=> tpm2-tools: fix CVE-2021-3565

meta-efi-secure-boot/recipes-bsp/shim/shim_git.bb
Fixes:
WARNING: shim-12+gitAUTOINC+5202f80c32-r0 do_fetch: Failed to fetch URL git://github.com/rhboot/shim.git, attempting MIRRORS if available
Signed-off-by: Mingli Yu <mingli.yu@windriver.com>
=> shim_git: fix the do_fetch warning

meta-encrypted-storage/recipes-tpm/cryptfs-tpm2/cryptfs-tpm2/0001-encrypt_secret.py-fix-for-python3.patch, meta-encrypted-storage/recipes-tpm/cryptfs-tpm2/cryptfs-tpm2_git.bb
Fixes:
encrypt_secret.py -i "H31i05" > "primary_key.secret" || exit 1
ERROR: Unable to encrypt the secret
Suggested-by: Kai Kang <kai.kang@windriver.com>
=> cryptfs-tpm2: fix encrypt_secret.py for python3

meta-signing-key/recipes-devtools/sbsigntool/sbsigntool_git.bb
The SRC_URI git://kernel.ubuntu.com/jk/sbsigntool no longer exists. I've updated the SRC_URI to point to the new location.
=> thud branch: fix sbsigningtool SRC_URI

meta-integrity/recipes-devtools/rpm/rpm-integrity.inc
enable this plugin will cause undeterministic build. whether to build
audit plugin depends on whether libaudit exists on the host
=> rpm-native: disable audit plugin

meta-efi-secure-boot/recipes-bsp/efitools/efitools.inc, meta-efi-secure-boot/recipes-bsp/seloader/seloader_git.bb, meta-efi-secure-boot/recipes-bsp/shim/shim_git.bb, meta-efi-secure-boot/recipes-extended/mokutil/mokutil_git.bb, meta-encrypted-storage/recipes-tpm/cryptfs-tpm2/cryptfs-tpm2_git.bb, meta-ids/recipes-ids/mtree/mtree_git.bb, meta-integrity/recipes-support/ima-inspect/ima-inspect_0.13.bb, meta-intel-sgx/recipes-kernel/intel-sgx-driver/intel-sgx-driver_2.1.bb, meta-signing-key/recipes-devtools/libsign/libsign_git.bb, meta-signing-key/recipes-devtools/sbsigntool/sbsigntool_git.bb, meta-tpm/recipes-tpm/openssl-tpm-engine/openssl-tpm-engine_0.5.0.bb, meta-tpm/recipes-tpm/pcr-extend/pcr-extend_git.bb, meta-tpm/recipes-tpm/tpm-quote-tools/tpm-quote-tools_git.bb, meta-tpm/recipes-tpm/tpm-tools/tpm-tools_git.bb, meta-tpm/recipes-tpm/trousers/trousers_git.bb, meta-tpm/recipes-tpm/tss-testsuite/tss-testsuite_git.bb, meta-tpm2/recipes-tpm/tpm2-abrmd/tpm2-abrmd_2.3.3.bb
Update SRC_URIs using git to include branch=master if no branch is set
and also to use protocol=https for github urls.
=> recipes: update SRC_URI branch and protocols

meta-signing-key/recipes-devtools/sbsigntool/sbsigntool_git.bb
Jeremy Kerr's sbsigntools are no longer hosted on git://kernel.ubuntu.com/jk/sbsigntool. A copy exists at git://git.kernel.org/pub/scm/linux/kernel/git/jejb/sbsigntools. This change is required to build meta-secure-core under sumo.
=> Updated the URI for Jeremy Kerr's sbsigntools

meta-efi-secure-boot/recipes-bsp/grub/grub-efi-efi-secure-boot.inc
Use variable GRUB_SECURE_BUILDIN to split grub secure
builtin option from GRUB_BUILDIN, then GRUB_BUILDIN will
not contain secure option for others grub-mkimage to
create no secure grub even though secure boot is enabled
=> grub-efi: split grub serure builtin option from GRUB_BUILDIN

meta-efi-secure-boot/recipes-bsp/grub/grub-efi-efi-secure-boot.inc
If tpm/tpm2 is enabled in DISTRO features, add the grub 'tpm' module to
GRUB_BUILDIN.
This is now required for secureboot to work w/ TPM is also enabled in a
BIOS.
=> (conditionally) add 'tpm' to list of grub built-in modules

meta-signing-key/conf/layer.conf
This fixes the problem of layers required order.
I am using [kas](https://github.com/siemens/kas) for building couple of projects and realized that it uses lexicographic order of the layers. This caused several issues; especially when my layer with Secure Boot keys ended up "above" `meta-signing-key` in `BBLAYERS`. By assigning `VENDOR_UUID` at the very end of parsing, we can have our layers in an arbitrary order.
If you are OK with this change, can you please, cherry-pick this to `gatesgarth` brach, too?
Thank you!
=> Set weak default value for VENDOR_UUID

meta/recipes-core/images/kernel-initramfs.bb
ALTERNATIVES_${PN} -> ALTERNATIVE:${PN}
=> kernel-initramfs: fix typo for ALTERNATIVE

meta-encrypted-storage/recipes-tpm/cryptfs-tpm2/cryptfs-tpm2/0001-env.mk-add-ld-option-noexecstack.patch, meta-encrypted-storage/recipes-tpm/cryptfs-tpm2/cryptfs-tpm2_git.bb
Add ld option '-z noexecstack' for cryptfs-tpm2 to fix link warnings:
ld: warning: secret_area.o: missing .note.GNU-stack section implies executable stack
ld: NOTE: This behaviour is deprecated and will be removed in a future version of the linker
=> cryptfs-tpm2: fix ld warnings with binutils 2.39

meta-efi-secure-boot/recipes-bsp/grub/grub-efi-efi-secure-boot.inc
Fix buildpaths warning:
WARNING: grub-efi-2.06-r0 do_package_qa: QA Issue: File /boot/efi/EFI/BOOT/x86_64-efi/modinfo.sh in package grub-efi contains reference to TMPDIR [buildpaths]
=> grub-efi: remove build host references from modinfo.sh

meta-efi-secure-boot/recipes-bsp/grub/grub-efi/0004-efi-chainloader-port-shim-to-grub.patch, meta-efi-secure-boot/recipes-bsp/grub/grub-efi/0005-efi-chainloader-use-shim-to-load-and-verify-an-image.patch, meta-efi-secure-boot/recipes-bsp/grub/grub-efi/0007-efi-chainloader-take-care-of-unload-undershim.patch
CVE-2022-28736 has 3 patches as below was conflicted with some meta-secure-boot layers patches. 
loader-efi-chainloader-Simplify-the-loader-state.patch 
commands-boot-Add-API-to-pass-context-to-loader.patch 
CVE-2022-28736-loader-efi-chainloader-Use-grub_loader_set_ex.patch
refresh patches to fix the conflict.
Signed-off-by: Xiangyu Chen <xiangyu.chen@windriver.com>
=> grub-efi: refresh patches for grub with fix of CVE-2022-28736

meta-tpm2/recipes-kernel/linux/linux-yocto-dev.bbappend, meta-tpm2/recipes-kernel/linux/linux-yocto-rt_5.%.bbappend, meta-tpm2/recipes-kernel/linux/linux-yocto_5.%.bbappend
There exists only linux-yocto-tpm2.inc. BPN will resolve to linux-yocto-rt and linux-yocto-dev which don't have a recipe specific include files.
Fixes bitbake recipe parsing errors like:
ERROR: ParseError at
/home/builder/src/build/../meta-secure-core/meta-tpm2/recipes-kernel/linux/linux-yocto-rt_5.%.bbappend:1: Could not include required file linux-yocto-rt-tpm2.inc ERROR: Parsing halted due to errors, see error messages above
Signed-off-by: Mikko Rapeli <mikko.rapeli@linaro.org>
=> linux-yocto*: fix require of include file

meta-integrity/recipes-kernel/linux/linux-yocto-dev.bbappend, meta-integrity/recipes-kernel/linux/linux-yocto-rt_5.%.bbappend
linux-yocto-integrity.inc is shared among linux-yocto linux-yocto-rt and linux-yocto-dev and cannot be found with ${BPN} in the latter two.
ERROR: ParseError at layers/meta-secure-core/meta-integrity/recipes-kernel/linux/linux-yocto-dev.bbappend:1: Could not include required file linux-yocto-dev-integrity.inc ERROR: ParseError at layers/meta-secure-core/meta-integrity/recipes-kernel/linux/linux-yocto-rt_5.%.bbappend:1: Could not include required file linux-yocto-rt-integrity.inc
Signed-off-by: He Zhe <zhe.he@windriver.com>
=> meta-integrity: Fix failure to find linux-yocto-integrity.inc

meta-efi-secure-boot/recipes-bsp/shim/shim/CVE-2022-28737-0001.patch, meta-efi-secure-boot/recipes-bsp/shim/shim/CVE-2022-28737-0002.patch, meta-efi-secure-boot/recipes-bsp/shim/shim_git.bb
shim: Buffer overflow when loading crafted EFI images.
Reference:
https://nvd.nist.gov/vuln/detail/CVE-2022-2873
Upstream-Status: Backport [https://github.com/rhboot/shim/commit/e99bdbb827a50cde019393d3ca1e89397db221a7, https://github.com/rhboot/shim/commit/159151b6649008793d6204a34d7b9c41221fb4b0]
CVE: CVE-2022-28737
Signed-off-by: Archana Polampalli <archana.polampalli@windriver.com>
=> shim: fix CVE-2022-28737
